### ISSUE TITLE
Hammer crashes after validating a resource with Java when using .exe

### ISSUE THREAD

**Issue by ArdonToonstra** [vadi2/Hammer#25]
**Describe the bug**
Hammer crashes without an error after validating a resource. Looks like it is caused by the JAVA validator because .NET works. 

**To Reproduce**
1. Validate a resource form Nictiz repo (condition or encounter example)
2. Select scope is profiles dir

**Comment by vadi2** [comment]
@ArdonToonstra Which example exactly is it, and what scope do you set it to?

**Comment by ArdonToonstra** [comment]
As you know, I am using the Nictiz STU3 Zib 2017 repo.

1. Open Hammer in .exe on Windows
2. File picker, select zib-Contact - example.xml from C:\git\nictiz-stu3-zib2017\Examples
3. File picker and set scope on "C:\git\nictiz-stu3-zib2017\Profiles - ZIB 2017"
4. Validate
5. .NET works, don't see any results for JAVA and then pfoef hammer gone

**Comment by vadi2** [comment]
Fixed with https://github.com/vadi2/Hammer/pull/43.

**Comment by vadi2** [comment]
Nope, still open. We pinned it down to the `.exe` being the problem - running `dotnet Hammer.dll` doesn't incur the crash.
